### ISSUE TITLE
Different Display Themes

### ISSUE THREAD

**Issue by theraffael** [sopra-fs22-group-09/basically-wordle-frontend#105]
**Story:** As a player I want to be able to change the display mode so that I can enjoy the app in the colors I love.

**Acceptance Criteria:**

- [ ] I can choose a dark theme.
- [ ] I can choose a light theme.
- [ ] I can choose a high contrast theme.
- [ ] I can choose a unicorn theme.
- [ ] I can choose a color-blind theme for visually impaired folks.

**Priority:** low
**Author:** SoPra Group 9
**Estimate:** 3h

**Comment by polatmete** [comment]
Couldn't be completed since we lost a group member in the beginning.
Please find further explanation in the group report.
