### ISSUE TITLE
Overhaul and refactor Modal rendering and routing logic

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-frontend#65]
The current state of modals is unmaintainable and flaky.
As a result of this, routing information is not accessible from within Modal components and Modals themselves are quite verbose. They should be refactored preferably into a reusable component that takes page content and displays it as a child of itself.

**Comment by polatmete** [comment]
Couldn't be completed since we lost a group member in the beginning.
Please find further explanation in the group report.
